package io.subbu.ai.firedrill.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Entity representing a match between a candidate and a job requirement.
 * Stores AI-generated matching scores and selection status for talent acquisition.
 */
@Entity
@Table(name = "candidate_matches")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CandidateMatch {

    /**
     * Primary key - unique identifier for the match
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    /**
     * The candidate being matched
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    private Candidate candidate;

    /**
     * The job requirement being matched against
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_requirement_id", nullable = false)
    private JobRequirement jobRequirement;

    /**
     * Overall matching score (0-100)
     */
    @Column(name = "match_score")
    private Double matchScore;

    /**
     * Skills matching score (0-100)
     */
    @Column(name = "skills_score")
    private Double skillsScore;

    /**
     * Experience matching score (0-100)
     */
    @Column(name = "experience_score")
    private Double experienceScore;

    /**
     * Education matching score (0-100)
     */
    @Column(name = "education_score")
    private Double educationScore;

    /**
     * Domain knowledge matching score (0-100)
     */
    @Column(name = "domain_score")
    private Double domainScore;

    /**
     * Detailed explanation of the match generated by AI
     */
    @Column(name = "match_explanation", columnDefinition = "TEXT")
    private String matchExplanation;

    /**
     * Whether the candidate has been selected by the talent acquisition team
     */
    @Column(name = "is_selected")
    @Builder.Default
    private Boolean isSelected = false;

    /**
     * Whether the candidate has been shortlisted for further review
     */
    @Column(name = "is_shortlisted")
    @Builder.Default
    private Boolean isShortlisted = false;

    /**
     * Notes from the talent acquisition team
     */
    @Column(name = "recruiter_notes", columnDefinition = "TEXT")
    private String recruiterNotes;

    /**
     * Timestamp when the match was created
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
